// 🤖 自动生成的模块注册文件
// 此文件由构建工具自动生成，请勿手动编辑！
// 要更新此文件，请运行: dart tool/generate_modules.dart

import 'package:sakiengine/src/core/project_module_loader.dart';

// 自动发现的模块导入
import 'package:sakiengine/soranouta/soranouta_module.dart'
    as soranouta_module;

/// 自动生成的模块工厂映射表
final Map<String, GameModuleFactory> _autoGeneratedModules = {
  'soranouta': () => soranouta_module.createProjectModule(),
};

/// 自动注册所有发现的模块
void registerAllDiscoveredModules() {
  final loader = ProjectModuleLoader();
  
  
  for (final entry in _autoGeneratedModules.entries) {
    try {
      loader.registerModule(entry.key, entry.value);
    } catch (e) {
    }
  }
  
}
